# nav_channel
wp_error_tolerance: 1.5 # acceptable distance for error when determining if we are at the goal, in meters.
gate_max_dist: 12.0 # max distance for gate 1, minimum distance for gate 2.
gate_max_width: 8.0 # max gap between buoys, accounts for diameter of buoys as well.
dist_past_second_gate: 5 # how far the asv will travel past the second gate for the task to be considered complete, in meters
dist_to_est_gate_2: 5 # how far from the first gate will we set our estimated second gate, in meters. Boat will travel here until it detects second gate
dist_from_gate: 2 # midpoint waypoints will be set this distance before and after the gate
colour_blind: true
# Switching Setpoint Modes
use_pixawk_reached: false
freq_disc_mode: true
freq_disc_count: 3
freq: 2 # in hertz

red_marker: "red_marker"
green_marker: "green_marker"